    integer(4) :: err
    call some_routine(err)
    end
